spring:
  application:
    name: payment-service

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8081

logging:
  level:
    root: INFO
    com.example: DEBUG

springdoc:
  api-docs:
    enabled: true
